library(bslib)
library(shiny)
library(shinycssloaders)
library(bsicons)
library(htmlwidgets)
library(htmltools)
library(dplyr)
library(ggplot2)
library(reactable)
library(ggiraph)
library(shinyWidgets)

app()
