# List of vars to load for each data set
default_vars <- c(
  "Organization Type", 
  "Subsector", 
  "Asset Size", 
  "Census Region", 
  "Census State",
  "Census County",
  "Census CBSA"
)


daf_vars <- c(
  "Number of Nonprofits",
  "Has DAF",
  "Number of DAFs",
  "Total Contributions",
  "Total Grants",
  "Total Value",
  "Proportion With DAFs"
)

data_server_args <- list(
  "Number" = list(
    "vars" = c(default_vars, "Number of Nonprofits", "Year"),
    id = "number",
    year_var = "Year",
    agg_var = "Number of Nonprofits",
    ytitle = "Number of Nonprofits",
    xtitle = "Year",
    title_prefix = "Number of",
  ),
  "Assets" = list(
    "vars" = c(default_vars, "Total Assets", "Year"),
    id = "assets",
    year_var = "Tax Year",
    agg_var = "Total Assets",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total Assets for",
  ),
  "Revenues" = list(
    "vars" = c(default_vars, "Total Revenues", "Year"),
    id = "revenues",
    year_var = "Tax Year",
    agg_var = "Total Revenues",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total Revenues for",
  ),
  "Expenses" = list(
    "vars" = c(default_vars, "Total Expenses", "Year"),
    id = "expenses",
    year_var = "Tax Year",
    agg_var = "Total Expenses",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total Expenses for",
  ),
  "Benefits" = list(
    "vars" = c(default_vars, "Total Benefits", "Year"),
    id = "benefits",
    year_var = "Tax Year",
    agg_var = "Total Benefits",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total Benefits for",
  ),
  "Payroll Taxes" = list(
    "vars" = c(default_vars, "Total Payroll Taxes", "Year"),
    id = "payroll_taxes",
    year_var = "Tax Year",
    agg_var = "Total Payroll Taxes",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total Payroll Taxes for",
  ),
  "Private Foundations" = list(
    "vars" = c(default_vars, "Total Contributions", "Year"),
    id = "private_foundations",
    year_var = "Tax Year",
    agg_var = "Total Contributions",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total Contributions for",
  ),
  "Number of DAFs" = list(
    "vars" = c(default_vars, "Number of DAFs", "Year"),
    id = "daf_number",
    year_var = "Tax Year",
    agg_var = "Number of DAFs",
    ytitle = "Number of DAFs",
    xtitle = "Tax Year",
    title_prefix = "Number of DAFs for",
  ),
  "DAF Contributions" = list(
    "vars" = c(default_vars, "Total Contributions", "Year"),
    id = "daf_contributions",
    year_var = "Tax Year",
    agg_var = "Total Contributions",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total DAF Contributions for",
  ),
  "DAF Grants" = list(
    "vars" = c(default_vars, "Total Grants", "Year"),
    id = "daf_grants",
    year_var = "Tax Year",
    agg_var = "Total Grants",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total DAF Grants for",
  ),
  "DAF Value" = list(
    "vars" = c(default_vars, "Total Value", "Year"),
    id = "daf_value",
    year_var = "Tax Year",
    agg_var = "Total Value",
    ytitle = "Dollars",
    xtitle = "Tax Year",
    title_prefix = "Total Value of DAFs for",
  ),
  "DAF Proportion" = list(
    "vars" = c(default_vars, "Has DAF", "Number of DAFs", "Year"),
    id = "daf_proportion",
    year_var = "Tax Year",
    agg_var = "Proportion With DAFs",
    ytitle = "Percentage",
    xtitle = "Tax Year",
    title_prefix = "Percentage with DAFs for",
  )
)